# Git Clone & Dependencies

In [1]:
import os

REPO_URL = "https://github.com/ChanceyGuo/idsc2026_team_top_coders.git"
REPO_DIR = "/kaggle/working/idsc2026_team_top_coders"

# clone repo
if not os.path.exists(REPO_DIR):
    !git clone {REPO_URL} {REPO_DIR}
else:
    %cd {REPO_DIR}
    !git pull --rebase
    %cd /kaggle/working

!pip -q install wfdb scikit-learn matplotlib

print("Git Clone & Dependencies completed.")
print("REPO_DIR =", REPO_DIR)

Cloning into '/kaggle/working/idsc2026_team_top_coders'...
remote: Enumerating objects: 83, done.
remote: Counting objects: 100% (83/83), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 83 (delta 46), reused 60 (delta 23), pack-reused 0 (from 0)
Receiving objects: 100% (83/83), 18.14 KiB | 4.54 MiB/s, done.
Resolving deltas: 100% (46/46), done.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.9/163.9 kB 5.0 MB/s eta 0:00:00
Git Clone & Dependencies completed.
REPO_DIR = /kaggle/working/idsc2026_team_top_coders

# Set Dataset Root Paths

In [2]:
import pandas as pd

DATA_ROOT = "/kaggle/input/datasets/chanceyguo/idsc2026-brugada-huca-raw"
REPO_DIR = "/kaggle/working/idsc2026_team_top_coders"

print("DATA_ROOT =", DATA_ROOT)
print("REPO_DIR  =", REPO_DIR)

print("\nCheck paths:")
print("DATA_ROOT exists:", os.path.exists(DATA_ROOT))
print("REPO_DIR exists :", os.path.exists(REPO_DIR))
print("metadata.csv exists:", os.path.exists(os.path.join(DATA_ROOT, "metadata.csv")))
print("metadata_dictionary.csv exists:", os.path.exists(os.path.join(DATA_ROOT, "metadata_dictionary.csv")))
print("files/files exists:", os.path.exists(os.path.join(DATA_ROOT, "files", "files")))

DATA_ROOT = /kaggle/input/datasets/chanceyguo/idsc2026-brugada-huca-raw
REPO_DIR  = /kaggle/working/idsc2026_team_top_coders

Check paths:
DATA_ROOT exists: True
REPO_DIR exists : True
metadata.csv exists: True
metadata_dictionary.csv exists: True
files/files exists: True

# Environment Check

In [3]:
!python "{REPO_DIR}/scripts/00_check_environment.py"

============================================================
IDSC2026 Team Top Coders - Environment Check
============================================================
Python: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]
Platform: Linux-6.6.113+-x86_64-with-glibc2.35
------------------------------------------------------------
numpy       : 2.0.2
pandas      : 2.3.3
matplotlib  : 3.10.0
sklearn     : 1.6.1
wfdb        : 4.3.1
============================================================
OK: environment check completed.

# Load Data & Sanity Checks

In [4]:
!python "{REPO_DIR}/scripts/01_load_data.py" --root "{DATA_ROOT}"

============================================================
01_load_data.py - Data path & metadata sanity check
============================================================
ROOT: /kaggle/input/datasets/chanceyguo/idsc2026-brugada-huca-raw
METADATA: /kaggle/input/datasets/chanceyguo/idsc2026-brugada-huca-raw/metadata.csv
DICT: /kaggle/input/datasets/chanceyguo/idsc2026-brugada-huca-raw/metadata_dictionary.csv
FILES_DIR: /kaggle/input/datasets/chanceyguo/idsc2026-brugada-huca-raw/files/files
------------------------------------------------------------
Rows: 363
HEA count: 363
DAT count: 363
Raw brugada unique: [0, 1, 2]
Raw brugada counts: {0: 287, 1: 69, 2: 7}
Binary counts (brugada>0): {0: 287, 1: 76}
------------------------------------------------------------
Saved: outputs/results/data_sanity_summary.json
OK: 01_load_data completed.

In [5]:
# check
!ls -lh outputs/results

total 4.0K
-rw-r--r-- 1 root root 243 Mar 14 21:02 data_sanity_summary.json

# Splits

In [6]:
!python "{REPO_DIR}/scripts/02_make_splits.py" --root "{DATA_ROOT}" --seed 42

============================================================
02_make_splits.py - Build binary label summary and train/val/test splits
============================================================
ROOT: /kaggle/input/datasets/chanceyguo/idsc2026-brugada-huca-raw
METADATA: /kaggle/input/datasets/chanceyguo/idsc2026-brugada-huca-raw/metadata.csv
SEED: 42
------------------------------------------------------------
Saved: outputs/results/data_summary.csv
Saved: outputs/splits/train.csv
Saved: outputs/splits/val.csv
Saved: outputs/splits/test.csv
------------------------------------------------------------
Split sizes: {'train': 254, 'val': 54, 'test': 55}
Class counts: {'total': 363, 'brugada': 76, 'normal': 287}
Overlap train&val: 0
Overlap train&test: 0
Overlap val&test: 0
Unique total: 363
OK: 02_make_splits completed.

In [7]:
!ls -lh outputs/results
!ls -lh outputs/splits

total 8.0K
-rw-r--r-- 1 root root  243 Mar 14 21:02 data_sanity_summary.json
-rw-r--r-- 1 root root 3.5K Mar 14 21:02 data_summary.csv
total 12K
-rw-r--r-- 1 root root  432 Mar 14 21:02 test.csv
-rw-r--r-- 1 root root 2.0K Mar 14 21:02 train.csv
-rw-r--r-- 1 root root  424 Mar 14 21:02 val.csv

# Explore One Record

In [8]:
!python "{REPO_DIR}/scripts/03_explore_data.py" --root "{DATA_ROOT}"

============================================================
03_explore_data.py - Read one ECG record
============================================================
ROOT: /kaggle/input/datasets/chanceyguo/idsc2026-brugada-huca-raw
FILES_DIR: /kaggle/input/datasets/chanceyguo/idsc2026-brugada-huca-raw/files/files
Chosen patient_id: 188981
------------------------------------------------------------
fs: 100
signals shape: (1200, 12)
leads: ['I', 'II', 'III', 'aVR', 'aVL', 'aVF', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6']
------------------------------------------------------------
Saved: outputs/figures/sample_ecg_188981.png
OK: 03_explore_data completed.

In [9]:
!ls -lh outputs/figures

total 104K
-rw-r--r-- 1 root root 102K Mar 14 21:02 sample_ecg_188981.png

# Visualize Signals

In [10]:
!python "{REPO_DIR}/scripts/04_visualize_signals.py" --root "{DATA_ROOT}"

============================================================
04_visualize_signals.py - Visualize 12-lead ECG
============================================================
Chosen patient_id: 188981
------------------------------------------------------------
fs: 100
signals shape: (1200, 12)
Saved: outputs/figures/visual_ecg_188981.png
OK: 04_visualize_signals completed.

In [11]:
!ls -lh outputs/figures

total 744K
-rw-r--r-- 1 root root 102K Mar 14 21:02 sample_ecg_188981.png
-rw-r--r-- 1 root root 637K Mar 14 21:02 visual_ecg_188981.png

# Preprocess Signals

In [12]:
!python "{REPO_DIR}/scripts/05_preprocess_signal.py" --root "{DATA_ROOT}"

============================================================
05_preprocess_signal.py - Basic ECG preprocessing
============================================================
Chosen patient_id: 188981
------------------------------------------------------------
original shape: (1200, 12)
transposed shape: (12, 1200)
normalized shape: (12, 1200)
processed shape: (12, 1200)
dtype: float32
Saved: outputs/figures/preprocessed_ecg_188981.png
OK: 05_preprocess_signal completed.

In [13]:
!ls -lh outputs/figures

total 960K
-rw-r--r-- 1 root root 215K Mar 14 21:02 preprocessed_ecg_188981.png
-rw-r--r-- 1 root root 102K Mar 14 21:02 sample_ecg_188981.png
-rw-r--r-- 1 root root 637K Mar 14 21:02 visual_ecg_188981.png

# Feature Engineering

In [14]:
!python "{REPO_DIR}/scripts/06_feature_engineering.py" --root "{DATA_ROOT}"

============================================================
06_feature_engineering.py - Build feature tables
============================================================
Train rows: 254
Val rows: 54
Test rows: 55
------------------------------------------------------------
Saved: outputs/results/features_train.csv
Saved: outputs/results/features_val.csv
Saved: outputs/results/features_test.csv
Feature dimension: 48
OK: 06_feature_engineering completed.

In [15]:
!ls -lh outputs/results

total 312K
-rw-r--r-- 1 root root  243 Mar 14 21:02 data_sanity_summary.json
-rw-r--r-- 1 root root 3.5K Mar 14 21:02 data_summary.csv
-rw-r--r-- 1 root root  45K Mar 14 21:02 features_test.csv
-rw-r--r-- 1 root root 205K Mar 14 21:02 features_train.csv
-rw-r--r-- 1 root root  45K Mar 14 21:02 features_val.csv

# Train Models

In [16]:
!python "{REPO_DIR}/scripts/07_train_model.py" --seed 42

============================================================
07_train_model.py - Train baseline models
============================================================
Train shape: (254, 48)
Val shape: (54, 48)
Test shape: (55, 48)
Feature count: 48
------------------------------------------------------------
Saved: models/lr_unweighted.pkl
Saved: models/lr_balanced.pkl
Saved: models/rf.pkl
Saved: outputs/results/feature_importance_rf.csv
Saved: outputs/results/lr_coefficients_unweighted.csv
Saved: outputs/results/lr_coefficients_balanced.csv
------------------------------------------------------------
OK: 07_train_model completed.

In [17]:
!ls -lh models

total 1.2M
-rw-r--r-- 1 root root 1.8K Mar 14 21:02 lr_balanced.pkl
-rw-r--r-- 1 root root 1.8K Mar 14 21:02 lr_unweighted.pkl
-rw-r--r-- 1 root root 1.1M Mar 14 21:02 rf.pkl

# Evaluate Models & Export Outputs

In [18]:
!python "{REPO_DIR}/scripts/08_evaluate_model.py" --seed 42 --threshold 0.5

============================================================
08_evaluate_model.py - Evaluate baseline models
============================================================
Threshold: 0.5
------------------------------------------------------------
Evaluating lr_unweighted ...
Evaluating lr_balanced ...
Evaluating rf ...
------------------------------------------------------------
Saved: outputs/results/experiment_summary_val.csv
Saved: outputs/results/experiment_summary_test.csv
OK: 08_evaluate_model completed.

In [19]:
!ls -lh outputs/results

total 380K
-rw-r--r-- 1 root root  243 Mar 14 21:02 data_sanity_summary.json
-rw-r--r-- 1 root root 3.5K Mar 14 21:02 data_summary.csv
-rw-r--r-- 1 root root  321 Mar 14 21:02 experiment_summary_test.csv
-rw-r--r-- 1 root root  350 Mar 14 21:02 experiment_summary_val.csv
-rw-r--r-- 1 root root 1.2K Mar 14 21:02 feature_importance_rf.csv
-rw-r--r-- 1 root root  45K Mar 14 21:02 features_test.csv
-rw-r--r-- 1 root root 205K Mar 14 21:02 features_train.csv
-rw-r--r-- 1 root root  45K Mar 14 21:02 features_val.csv
-rw-r--r-- 1 root root 1.2K Mar 14 21:02 lr_coefficients_balanced.csv
-rw-r--r-- 1 root root 1.2K Mar 14 21:02 lr_coefficients_unweighted.csv
-rw-r--r-- 1 root root  145 Mar 14 21:02 metrics_lr_balanced_test.csv
-rw-r--r-- 1 root root  147 Mar 14 21:02 metrics_lr_balanced_val.csv
-rw-r--r-- 1 root root  120 Mar 14 21:02 metrics_lr_unweighted_test.csv
-rw-r--r-- 1 root root  163 Mar 14 21:02 metrics_lr_unweighted_val.csv
-rw-r--r-- 1 root root  154 Mar 14 21:02 metrics_rf_test.csv
-rw-r--r-- 1 root root  138 Mar 14 21:02 metrics_rf_val.csv
-rw-r--r-- 1 root root  626 Mar 14 21:02 misclassified_lr_balanced_test.csv
-rw-r--r-- 1 root root  385 Mar 14 21:02 misclassified_lr_unweighted_test.csv
-rw-r--r-- 1 root root  262 Mar 14 21:02 misclassified_rf_test.csv
-rw-r--r-- 1 root root 1.8K Mar 14 21:02 predictions_lr_balanced_test.csv
-rw-r--r-- 1 root root 1.8K Mar 14 21:02 predictions_lr_unweighted_test.csv
-rw-r--r-- 1 root root  992 Mar 14 21:02 predictions_rf_test.csv

In [20]:
!ls -lh outputs/figures

total 1.5M
-rw-r--r-- 1 root root  39K Mar 14 21:02 cm_lr_balanced_test.png
-rw-r--r-- 1 root root  38K Mar 14 21:02 cm_lr_balanced_val.png
-rw-r--r-- 1 root root  41K Mar 14 21:02 cm_lr_unweighted_test.png
-rw-r--r-- 1 root root  41K Mar 14 21:02 cm_lr_unweighted_val.png
-rw-r--r-- 1 root root  38K Mar 14 21:02 cm_rf_test.png
-rw-r--r-- 1 root root  39K Mar 14 21:02 cm_rf_val.png
-rw-r--r-- 1 root root 215K Mar 14 21:02 preprocessed_ecg_188981.png
-rw-r--r-- 1 root root  51K Mar 14 21:02 roc_lr_balanced_test.png
-rw-r--r-- 1 root root  51K Mar 14 21:02 roc_lr_balanced_val.png
-rw-r--r-- 1 root root  51K Mar 14 21:02 roc_lr_unweighted_test.png
-rw-r--r-- 1 root root  51K Mar 14 21:02 roc_lr_unweighted_val.png
-rw-r--r-- 1 root root  50K Mar 14 21:02 roc_rf_test.png
-rw-r--r-- 1 root root  51K Mar 14 21:02 roc_rf_val.png
-rw-r--r-- 1 root root 102K Mar 14 21:02 sample_ecg_188981.png
-rw-r--r-- 1 root root 637K Mar 14 21:02 visual_ecg_188981.png

# Output Review

In [21]:
pd.read_csv("outputs/results/experiment_summary_val.csv")

           model split  accuracy  precision    recall        f1   roc_auc
0  lr_unweighted   val  0.814815   0.666667  0.181818  0.285714  0.644820
1    lr_balanced   val  0.629630   0.285714  0.545455  0.375000  0.657505
2             rf   val  0.796296   0.500000  0.181818  0.266667  0.750529

In [22]:
pd.read_csv("outputs/results/experiment_summary_test.csv")

           model split  accuracy  precision    recall        f1   roc_auc
0  lr_unweighted  test  0.800000   0.600000  0.250000  0.352941  0.629845
1    lr_balanced  test  0.654545   0.315789  0.500000  0.387097  0.624031
2             rf  test  0.763636   0.333333  0.083333  0.133333  0.755814

In [23]:
pd.read_csv("outputs/results/lr_coefficients_balanced.csv").head(10)

  feature  coefficient
0     f25     1.000799
1     f23    -0.976247
2     f45     0.838904
3     f41     0.834216
4     f47     0.774887
5     f34    -0.645290
6     f07     0.612461
7     f02    -0.607552
8     f14     0.595892
9     f37     0.574475